# Generated by Django 5.1.3 on 2025-03-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salgrade',
            fields=[
                ('GRADE', models.IntegerField(primary_key=True, serialize=False)),
                ('LOSAL', models.DecimalField(decimal_places=3, max_digits=10)),
                ('HISAL', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
